on:
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Push files
        # You may pin to the exact commit or the version.
  # uses: anvil-solutions/Fast-FTP-Action@de62eeaf1c409a96c7304f3bba8bf8194d0fa98f
      uses: anvil-solutions/Fast-FTP-Action@2.1.3
      with:
    # FTP server name (you may need to specify a port)
        server: ${{ secrets.FTP_URL }}
    # FTP account username
        username: ${{ secrets.FTP_USERNAME }}
    # FTP account password
        password: ${{ secrets.FTP_PASSWORD }}
    # Protocol used to deploy (ftp or sftp)
        method: ftp
    # The remote folder to copy to, deafults to root FTP folder
        remote_dir: /
          
